language: csharp
mono: none
dotnet: 3.1
script:
  - npm install
  - npm run build
  - npm test
node_js:
  - "12.16.3"
deploy:
  - skip_cleanup: true
    provider: script
    script: npm run deploy
    on:
      branch: master
  - skip_cleanup: true
    provider: script
    script: npm run deploy-branch
    on:
      all_branches: true
      condition: '"$TRAVIS_BRANCH" != "master" && "$TRAVIS_BRANCH" != "gh-pages"'

