on:
  push:
    branches-ignore:
      - master

env:
  CI: true
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  validate-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm i --ignore-scripts

      - name: Build
        run: npm run build

      - name: Validate schema
        run: npm run test
  
      - name: Deploy branch
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config user.name "$GITHUB_ACTOR"  
          npm run deploy-branch

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d .tmp -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
