on:
  push:
    branches-ignore:
      - master

env:
  CI: true
  
jobs:
  validate-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm i --ignore-scripts

      - name: Build
        run: npm run build

      - name: Validate schema
        run: npm run test
  
      - name: Deploy branch
        run: npm run deploy-branch
